const K="DQ_FINAL";let D=JSON.parse(localStorage.getItem(K)||"null")||{xp:0,coins:0,streak:0,best:0,last:"",days:0,quests:0,workouts:[],qd:{},notes:{},ach:{},shop:{},name:"Discipline Warrior",goal:100,tab:"home"};
const T=()=>new Date().toISOString().slice(0,10), L=()=>Math.floor(D.xp/500)+1, save=()=>localStorage.setItem(K,JSON.stringify(D));
function toast(s){let x=document.createElement("div");x.className="toast";x.textContent=s;document.body.append(x);setTimeout(()=>x.remove(),1400)}
function boot(){let t=T();if(D.last!==t){if(D.last){let gap=Math.round((new Date(t)-new Date(D.last))/864e5);D.streak=gap===1?D.streak+1:1}else D.streak=1;D.best=Math.max(D.best,D.streak);D.last=t;D.days++;save()}}
boot();
const Q=[["workout","💪","Complete a workout",60],["strength","⚡","Strength practice",25],["focus","🎯","Deep focus",35],["move","🚶","Move for 10 minutes",25],["recovery","🌙","Recovery check",20],["journal","📝","Journal today",35],["self","🛡️","Self-control streak",40]];
const EX=["Push-ups","Pull-ups","Squats","Lunges","Plank","Pike push-ups","Glute bridge","Calf raises"];
const ACH=[["first","🌱","First Quest",()=>D.quests>=1],["s7","🔥","7-Day Streak",()=>D.streak>=7],["s30","🏆","30-Day Streak",()=>D.best>=30],["w10","💪","Ten Sessions",()=>D.workouts.length>=10],["xp1","⭐","1K XP",()=>D.xp>=1000],["lv5","🔮","Level 5",()=>L()>=5],["q100","🎯","Quest Master",()=>D.quests>=100]];
function check(){ACH.forEach(a=>{if(!D.ach[a[0]]&&a[3]()){D.ach[a[0]]=1;D.coins+=25;setTimeout(()=>toast("🏆 "+a[2]+" +25 coins"),200)}})}
function add(n){D.xp+=n;D.coins+=Math.max(1,Math.floor(n/10));check();save();toast("+"+n+" XP");render()}
function done(id){return (D.qd[T()]||[]).includes(id)}
function quest(id){if(done(id))return toast("Already done today");D.qd[T()]=D.qd[T()]||[];D.qd[T()].push(id);D.quests++;add(Q.find(x=>x[0]===id)[3])}
function nav(){return `<nav class="nav">${[["⌂","Home","home"],["⚔","Quests","quests"],["💪","Workout","workout"],["📊","Stats","stats"],["🗺","Map","map"],["☰","More","more"]].map(x=>`<button class="${D.tab===x[2]?"active":""}" onclick="go('${x[2]}')"><b>${x[0]}</b>${x[1]}</button>`).join("")}</nav>`}
function head(a,b){return `<div class="top"><div class="row"><div><div class="brand">${a}</div><div class="muted tiny">${b}</div></div><div>LV ${L()}<br>🪙 ${D.coins}</div></div></div>`}
function hero(){let p=(D.xp%500)/5;return `<div class="card hero"><div class="row"><div><div class="label">LEVEL</div><div class="level">${L()}</div></div><b>🔥 ${D.streak}</b></div><div class="xp"><i style="width:${p}%"></i></div><div class="row tiny muted"><span>${D.xp%500}/500 XP</span><span>${500-(D.xp%500)} to next</span></div></div>`}
function qc(q){let d=done(q[0]);return `<div class="card quest"><div class="qicon">${q[1]}</div><div class="grow"><b>${q[2]}</b><div class="reward">+${q[3]} XP</div></div><button class="btn ${d?"secondary":""}" onclick="quest('${q[0]}')">${d?"✓":"GO"}</button></div>`}
function home(){let total=(D.qd[T()]||[]).reduce((s,id)=>s+(Q.find(q=>q[0]===id)?.[3]||0),0);return head("Discipline Quest","Turn real actions into game progress.")+hero()+`<div class="grid2"><div class="stat"><div class="big">🔥 ${D.streak}</div><div class="label">STREAK</div></div><div class="stat"><div class="big">${D.days?Math.min(100,Math.round(Object.keys(D.qd).length/D.days*100)):0}%</div><div class="label">CONSISTENCY</div></div></div><div class="section">TODAY</div>${Q.slice(0,4).map(qc).join("")}<div class="card"><b>🎯 Daily XP Goal</b><div class="muted tiny">${total}/${D.goal} XP from today's quests</div></div>`}
function quests(){let w=D.workouts.filter(x=>(new Date(T())-new Date(x.date))/864e5<7).length;let p=Math.min(100,w/4*100);return head("Quests","Daily missions and the weekly boss.")+`<div class="section">DAILY MISSIONS</div>${Q.map(qc).join("")}<div class="section">WEEKLY BOSS</div><div class="card hero"><div class="row"><div><b>🐉 The Lazy Beast</b><br><small class="muted">4 workouts this week</small></div><b>${Math.round(p)}%</b></div><div class="bar"><i style="width:${p}%"></i></div>${p>=100?'<button class="btn" style="margin-top:12px" onclick="boss()">Claim 250 XP</button>':""}</div>`}
function boss(){if(D.shop.boss)return toast("Already claimed");D.shop.boss=1;add(250)}
function workout(){return head("Workout","Sets, reps, PRs and history.")+`<div class="card"><div class="field"><label>Exercise</label><select id="ex">${EX.map(x=>`<option>${x}</option>`).join("")}</select></div><div class="grid2" style="margin:0"><div class="field"><label>Sets</label><input id="sets" type="number" value="3" min="1"></div><div class="field"><label>Reps / sec</label><input id="reps" type="number" value="10" min="1"></div></div><button class="btn" onclick="log()">Log workout</button></div><div class="section">RECENT</div><div class="card">${D.workouts.slice(-8).reverse().map(w=>`<div class="achievement"><span class="badge">💪</span><div><b>${w.ex}</b><br><small>${w.sets} × ${w.reps} • ${w.date}</small></div>${w.pr?"<span>🏆</span>":""}</div>`).join("")||'<div class="muted">No sessions yet.</div>'}</div>`}
function log(){let ex=document.getElementById("ex").value,s=+document.getElementById("sets").value,r=+document.getElementById("reps").value;if(!s||!r)return;let old=Math.max(0,...D.workouts.filter(w=>w.ex===ex).map(w=>w.reps));let pr=old>0&&r>old;D.workouts.push({date:T(),ex,sets:s,reps:r,pr});if(!done("workout")){D.qd[T()]=D.qd[T()]||[];D.qd[T()].push("workout");D.quests++}save();add(pr?90:60)}
function stats(){let cells="",d=new Date();d.setDate(1);let m=d.getMonth(),st=d.getDay();for(let i=0;i<st;i++)cells+="<div></div>";while(d.getMonth()===m){let k=d.toISOString().slice(0,10),g=(D.qd[k]||[]).length>0;cells+=`<div class="day ${g?"good":""} ${k===T()?"today":""}">${d.getDate()}</div>`;d.setDate(d.getDate()+1)}return head("Stats","Measure consistency, not perfection.")+`<div class="grid2"><div class="stat"><div class="big">${D.xp}</div><div class="label">XP</div></div><div class="stat"><div class="big">${D.workouts.length}</div><div class="label">WORKOUTS</div></div><div class="stat"><div class="big">${D.best}</div><div class="label">BEST STREAK</div></div><div class="stat"><div class="big">${D.quests}</div><div class="label">QUESTS</div></div></div><div class="section">THIS MONTH</div><div class="card"><div class="calendar">${cells}</div></div>`}
function map(){let z=[["Village of Beginnings",1],["Focus Forest",4],["Strength Mountain",8],["Discipline Castle",12],["Mastery Realm",20]];return head("Progress Map","Unlock zones by leveling up.")+'<div class="card">'+z.map(x=>`<div class="zone ${L()>=x[1]?"":"lock"}"><b>${L()>=x[1]?"✓":"🔒"} ${x[0]}</b><br><small class="muted">Unlock at level ${x[1]}</small></div>`).join("")+'</div>'}
function more(){return head("More","Achievements, shop, journal and backup.")+`<div class="card">${ACH.map(a=>`<div class="achievement"><span class="badge">${D.ach[a[0]]?a[1]:"○"}</span><div><b>${a[2]}</b><br><small class="muted">${D.ach[a[0]]?"UNLOCKED":"LOCKED"}</small></div></div>`).join("")}</div><div class="card"><b>📝 Journal</b><div class="field"><textarea id="note" rows="4" placeholder="Write today's note...">${D.notes[T()]||""}</textarea></div><button class="btn" onclick="note()">Save note</button></div><div class="card"><b>🪙 Shop</b><div class="row" style="margin-top:12px"><span>⚡ XP Token — 100 coins</span><button class="btn" onclick="buy()">Buy</button></div></div><div class="card"><b>⚙️ Settings & Backup</b><div class="field"><label>Name</label><input id="nm" value="${D.name}"></div><div class="field"><label>Daily XP goal</label><input id="goal" type="number" value="${D.goal}"></div><button class="btn" onclick="settings()">Save</button><button class="btn secondary" onclick="backup()" style="margin-left:6px">Export</button><input id="imp" type="file" accept=".json" style="display:none" onchange="restore(this)"><button class="btn secondary" onclick="document.getElementById('imp').click()" style="margin:6px 0 0 6px">Import</button></div>`}
function note(){D.notes[T()]=document.getElementById("note").value;save();toast("Journal saved");render()}
function settings(){D.name=document.getElementById("nm").value||"Discipline Warrior";D.goal=+document.getElementById("goal").value||100;save();toast("Saved");render()}
function buy(){if(D.coins<100)return toast("Need 100 coins");D.coins-=100;D.xp+=100;save();toast("XP Token used");render()}
function backup(){let a=document.createElement("a"),b=new Blob([JSON.stringify(D)],{type:"application/json"});a.href=URL.createObjectURL(b);a.download="discipline-quest-backup.json";a.click()}
function restore(i){let f=i.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(typeof x.xp!=="number")throw 0;D=x;save();render();toast("Backup restored")}catch(e){toast("Invalid backup")}};r.readAsText(f)}
function go(t){D.tab=t;save();render()}
function render(){let b={home,quests,workout,stats,map,more}[D.tab]();document.getElementById("app").innerHTML=`<main class="app">${b}</main>${nav()}`}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});render();