const A={xp:+localStorage.xp||0,coins:+localStorage.coins||0,streak:+localStorage.streak||0,active:+localStorage.active||0,days:+localStorage.days||1,workouts:+localStorage.workouts||0,quests:+localStorage.quests||0,pr:+localStorage.pr||0,notes:localStorage.notes||'',last:localStorage.last||'',done:JSON.parse(localStorage.done||'[]'),tab:localStorage.tab||'home'};
const today=()=>new Date().toISOString().slice(0,10);
function save(){Object.entries(A).forEach(([k,v])=>{if(k!=='tab'&&typeof v!=='object')localStorage[k]=v});localStorage.done=JSON.stringify(A.done)}
if(A.last!==today()){A.done=[];A.days++;A.active++;if(A.last){let d=(new Date(today())-new Date(A.last))/86400000;if(d<=1)A.streak++;else A.streak=1}else A.streak=1;A.last=today();save()}
const quests=[['💪','Complete a workout',50],['⚡','Strength practice',20],['📚','Focused study',30],['🚶','10-minute movement',25],['😴','Recovery check',20],['📝','Journal today',35]];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function level(){return Math.floor(A.xp/500)+1} function pct(){return Math.min(100,Math.round(A.active/A.days*100))}
function addXP(n){A.xp+=n;A.coins+=Math.floor(n/10);save();toast('+'+n+' XP  •  +'+Math.floor(n/10)+' coins');render()}
function toast(s){let x=document.createElement('div');x.className='toast';x.textContent=s;document.body.appendChild(x);setTimeout(()=>x.remove(),1300)}
function complete(i){if(A.done.includes(i))return;A.done.push(i);A.quests++;save();addXP(quests[i][2])}
function nav(){return `<nav class="nav">${[['⌂','Home'],['⚔','Quests'],['💪','Workout'],['◈','Stats'],['◆','Map'],['●','Profile']].map((n,i)=>`<button class="${A.tab===['home','quests','workout','stats','map','profile'][i]?'active':''}" onclick="go('${['home','quests','workout','stats','map','profile'][i]}')"><b>${n[0]}</b>${n[1]}</button>`).join('')}</nav>`}
function header(t,s){return `<div class="top"><div class="row"><div><div class="title">${t}</div><div class="muted">${s}</div></div><div style="text-align:right"><b>LV ${level()}</b><br><small>★ ${A.coins}</small></div></div></div>`}
function home(){let left=500-(A.xp%500);return header('Discipline Quest','Build consistency. Earn your next level.')+`<div class="card hero"><small>LEVEL ${level()}</small><h2>${A.xp} XP</h2><div class="xpbar"><i style="width:${(A.xp%500)/5}%"></i></div><div class="muted" style="margin-top:8px">${left} XP to next level</div></div><div class="grid2"><div class="stat"><div class="num">🔥 ${A.streak}</div><small>DAY STREAK</small></div><div class="stat"><div class="num">${pct()}%</div><small>CONSISTENCY</small></div></div><div class="section">TODAY'S FOCUS</div><div class="list">${quests.slice(0,4).map((q,i)=>qrow(q,i)).join('')}</div>`}
function qrow(q,i){let d=A.done.includes(i);return `<div class="card quest"><div class="check ${d?'done':''}" onclick="complete(${i})">${d?'✓':q[0]}</div><div class="grow"><b>${q[1]}</b><div class="reward">+${q[2]} XP</div></div><span class="pill">${d?'DONE':'GO'}</span></div>`}
function questsPage(){return header('Quests','Complete actions, not just taps.')+`<div class="section">DAILY QUESTS</div><div class="list">${quests.map((q,i)=>qrow(q,i)).join('')}</div><div class="card hero"><h2>🐉 Weekly Boss</h2><div class="muted">The Lazy Beast</div><p class="muted">4 workouts • 5 focus sessions • 3 recovery days</p><b style="color:#a895ff">+500 XP</b></div>`}
function workout(){return header('Workout','Log your real training.')+`<div class="section">QUICK LOG</div><div class="list">${['Push-ups','Pull-ups','Squats','Plank'].map(x=>`<div class="card row"><b>${x}</b><button class="btn secondary" onclick="log('${x}')">Log</button></div>`).join('')}</div><div class="card"><b>🏆 Best pull-ups: ${A.pr}</b><br><small>Workouts completed: ${A.workouts}</small></div>`}
function log(x){let n=prompt(x+' — enter reps/time');if(!n)return;n=Number(n);if(!Number.isFinite(n))return;A.workouts++;if(x==='Pull-ups'&&n>A.pr){A.pr=n;toast('🏆 New Personal Record!')}else toast('+15 XP');save();addXP(15)}
function stats(){let rank=level()>=20?'MASTER':level()>=10?'ELITE':level()>=5?'WARRIOR':'ROOKIE';return header('Stats','Your progress over time.')+`<div class="grid2">${[['XP',A.xp],['LEVEL',level()],['WORKOUTS',A.workouts],['QUESTS',A.quests],['STREAK',A.streak],['CONSISTENCY',pct()+'%']].map(x=>`<div class="stat"><small>${x[0]}</small><div class="num">${x[1]}</div></div>`).join('')}</div><div class="card"><small>RANK</small><h2 style="color:#a895ff">${rank}</h2><p class="muted">Consistency beats perfection.</p></div>`}
function map(){let zones=['Village of Beginnings','Focus Forest','Strength Mountain','Discipline Castle','Mastery Realm'];return header('Progress Map','Every milestone unlocks the next zone.')+`<div class="card map">${zones.map((z,i)=>{let open=level()>=1+i*4;return `<div class="zone ${open?'':'locked'}"><b>${open?'✓':'🔒'} ${z}</b><br><small>${open?'Unlocked':'Reach level '+(1+i*4)}</small></div>`}).join('')}</div>`}
function profile(){let ach=[['🏆','First Quest',A.quests>=1],['🔥','7 Day Consistency',A.streak>=7],['💪','10 Workouts',A.workouts>=10],['⭐','Level 5',level()>=5],['⚔','100 Quests',A.quests>=100],['🐉','Boss Slayer',false]];return header('Profile','Your personal discipline dashboard.')+`<div class="card"><h2>DISCIPLINE WARRIOR</h2><small>Level ${level()} • ${A.xp} XP • ${A.coins} coins</small><p class="muted">Offline-first • stored on this phone</p></div><div class="section">ACHIEVEMENTS</div><div class="card">${ach.map(a=>`<div class="achievement"><span class="emoji">${a[2]?a[0]:'○'}</span><div><b>${a[1]}</b><br><small>${a[2]?'UNLOCKED':'LOCKED'}</small></div></div>`).join('')}</div><div class="card"><b>📝 Journal</b><br><small>${A.notes?esc(A.notes):'No note today.'}</small><br><button class="btn" style="margin-top:12px" onclick="journal()">Add note</button></div>`}
function journal(){let n=prompt('Today’s note',A.notes);if(n!==null){A.notes=n;save();render()}}
function go(t){A.tab=t;localStorage.tab=t;render()}
function render(){let p={home,quests:questsPage,workout,stats,map,profile}[A.tab]();document.getElementById('app').innerHTML=p+nav()}
render();